# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estate.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.PositiveIntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=120)),
                ('town', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to=estate.utils.upload_place_images_dir)),
            ],
        ),
        migrations.CreateModel(
            name='OtherField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('field_type', models.CharField(choices=[('t', 'Text'), ('n', 'Number')], default='t', max_length=1)),
                ('field_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('purchase_type', models.CharField(choices=[('b', 'BUY'), ('r', 'RENT')], default='b', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('age', models.CharField(choices=[('o', 'OLD'), ('n', 'NEW')], default='o', max_length=1)),
                ('no_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='image thumbnail', null=True, upload_to=estate.utils.upload_display_image_dir)),
                ('image', models.ImageField(blank=True, help_text='display image', null=True, upload_to=estate.utils.upload_thumbnail_dir)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='estate.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='estate.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RentedPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.Place')),
                ('duration', models.PositiveIntegerField()),
                ('is_rented', models.BooleanField(default=False)),
                ('duration_type', models.CharField(choices=[('m', 'Month'), ('y', 'Year'), ('w', 'Week'), ('d', 'Day')], default='m', max_length=1)),
                ('total_duration_months', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('estate.place',),
        ),
        migrations.CreateModel(
            name='SalePlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estate.Place')),
                ('is_sold', models.BooleanField(default=False)),
            ],
            bases=('estate.place',),
        ),
        migrations.AddField(
            model_name='threedview',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d_views', to='estate.Place'),
        ),
        migrations.AddField(
            model_name='question',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='estate.Place'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='estate.UserProfile'),
        ),
        migrations.AddField(
            model_name='place',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='places', to='estate.Facility'),
        ),
        migrations.AddField(
            model_name='place',
            name='other_fields',
            field=models.ManyToManyField(blank=True, related_name='places', to='estate.OtherField'),
        ),
        migrations.AddField(
            model_name='place',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='estate.PropertyType'),
        ),
        migrations.AddField(
            model_name='place',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_uploads', to='estate.UserProfile'),
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.Place'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='estate.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='estate.UserProfile'),
        ),
        migrations.AddField(
            model_name='address',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate.Place'),
        ),
    ]
