# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20170312_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PropertyImage',
        ),
        migrations.RemoveField(
            model_name='place',
            name='purchase_type',
        ),
    ]
