# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_facility_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterUniqueTogether(
            name='otherfield',
            unique_together=set([('field_name', 'field_type', 'field_value')]),
        ),
    ]
