# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_auto_20170314_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([('name', 'quantity')]),
        ),
    ]
