# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_auto_20170315_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=75849, max_length=10),
            preserve_default=False,
        ),
    ]
