# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='no_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='place',
            name='no_rooms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Rooms'),
        ),
    ]
