# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_auto_20170412_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='user_profile',
        ),
    ]
