# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_auto_20170413_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
    ]
