# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_auto_20170414_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-date']},
        ),
    ]
