# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0014_auto_20170414_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('user_profile', 'question')]),
        ),
    ]
