# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_auto_20170414_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentableplace',
            name='place_ptr',
        ),
        migrations.AlterModelOptions(
            name='buyableplace',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RentablePlace',
        ),
    ]
