# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_auto_20170510_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyableplace',
            options={},
        ),
    ]
