# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0018_auto_20170510_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
