# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_auto_20170513_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingschedule',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
