# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0024_auto_20170514_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingschedule',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Votre numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='quantity',
            field=models.CharField(max_length=6),
        ),
    ]
