# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0028_auto_20170524_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='year_constructed',
            field=models.PositiveIntegerField(max_length=4, verbose_name='Année de construction'),
        ),
    ]
