# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0029_auto_20170524_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproperty',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_properties', to='estate.BookingSchedule'),
        ),
    ]
