# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0031_auto_20170525_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingschedule',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_schedules', to='estate.Place'),
        ),
    ]
