# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0032_auto_20170525_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproperty',
            name='client_type',
            field=models.CharField(choices=[('VE', 'Vendre'), ('ES', 'Estimer')], default='VE', max_length=2),
        ),
    ]
