# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0033_clientproperty_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='client_type',
            field=models.CharField(blank=True, choices=[('VE', 'Vendre'), ('ES', 'Estimer')], default='VE', max_length=2),
        ),
    ]
