# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0034_auto_20170525_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='area',
            field=models.PositiveIntegerField(verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='clientproperty',
            name='land_area',
            field=models.PositiveIntegerField(verbose_name='Surface terrain'),
        ),
        migrations.AlterField(
            model_name='clientproperty',
            name='postal_code',
            field=models.PositiveIntegerField(verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='clientproperty',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Prix demandé'),
        ),
    ]
