# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0035_auto_20170526_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='scheduled_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookingschedule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingschedule',
            name='schedule_date',
            field=models.DateTimeField(error_messages={'required': 'ce champ est requis'}, verbose_name='Date du calendrier'),
        ),
    ]
