# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0036_auto_20170530_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdownload',
            old_name='is_valid',
            new_name='is_validated',
        ),
    ]
