# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0039_auto_20170601_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdownload',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.PropertyDocument'),
        ),
    ]
