# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0041_auto_20170604_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='year_constructed',
            field=models.PositiveIntegerField(verbose_name='Année de construction'),
        ),
    ]
