# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0042_auto_20170604_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyableplace',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
